package com.aistock.research.shortterm;

import java.math.BigDecimal;
import java.time.LocalDate;

public record ShortTermTechnicalSnapshot(
        LocalDate tradeDate,
        BigDecimal ma5,
        BigDecimal ma10,
        BigDecimal ma20,
        BigDecimal ma60,
        BigDecimal ma20SlopePercent,
        BigDecimal ma60SlopePercent,
        BigDecimal previousHigh20,
        BigDecimal previousHigh60,
        BigDecimal breakoutFromPreviousHigh20Percent,
        BigDecimal previousRange20Percent,
        BigDecimal high120,
        BigDecimal low120,
        BigDecimal volumeRatio5,
        BigDecimal volumeRatio20,
        BigDecimal rangePosition60,
        BigDecimal rangePosition120,
        BigDecimal distanceToMa20Percent,
        BigDecimal drawdownFrom120HighPercent,
        BigDecimal todayAmplitudePercent,
        int consecutiveAboveMa20Days,
        String rightSideSignal,
        ShortTermGoldenCrossSnapshot goldenCross,
        BigDecimal atr14Percent,
        BigDecimal recentSupportPrice,
        ShortTermMomentumQuality momentumQuality
) {
    public ShortTermTechnicalSnapshot(
            LocalDate tradeDate,
            BigDecimal ma5,
            BigDecimal ma10,
            BigDecimal ma20,
            BigDecimal ma60,
            BigDecimal ma20SlopePercent,
            BigDecimal ma60SlopePercent,
            BigDecimal previousHigh20,
            BigDecimal previousHigh60,
            BigDecimal breakoutFromPreviousHigh20Percent,
            BigDecimal previousRange20Percent,
            BigDecimal high120,
            BigDecimal low120,
            BigDecimal volumeRatio5,
            BigDecimal volumeRatio20,
            BigDecimal rangePosition60,
            BigDecimal rangePosition120,
            BigDecimal distanceToMa20Percent,
            BigDecimal drawdownFrom120HighPercent,
            BigDecimal todayAmplitudePercent,
            int consecutiveAboveMa20Days,
            String rightSideSignal,
            ShortTermGoldenCrossSnapshot goldenCross,
            BigDecimal atr14Percent,
            BigDecimal recentSupportPrice
    ) {
        this(
                tradeDate,
                ma5,
                ma10,
                ma20,
                ma60,
                ma20SlopePercent,
                ma60SlopePercent,
                previousHigh20,
                previousHigh60,
                breakoutFromPreviousHigh20Percent,
                previousRange20Percent,
                high120,
                low120,
                volumeRatio5,
                volumeRatio20,
                rangePosition60,
                rangePosition120,
                distanceToMa20Percent,
                drawdownFrom120HighPercent,
                todayAmplitudePercent,
                consecutiveAboveMa20Days,
                rightSideSignal,
                goldenCross,
                atr14Percent,
                recentSupportPrice,
                ShortTermMomentumQuality.unavailable()
        );
    }

    public ShortTermTechnicalSnapshot withMomentumQuality(ShortTermMomentumQuality quality) {
        return new ShortTermTechnicalSnapshot(
                tradeDate,
                ma5,
                ma10,
                ma20,
                ma60,
                ma20SlopePercent,
                ma60SlopePercent,
                previousHigh20,
                previousHigh60,
                breakoutFromPreviousHigh20Percent,
                previousRange20Percent,
                high120,
                low120,
                volumeRatio5,
                volumeRatio20,
                rangePosition60,
                rangePosition120,
                distanceToMa20Percent,
                drawdownFrom120HighPercent,
                todayAmplitudePercent,
                consecutiveAboveMa20Days,
                rightSideSignal,
                goldenCross,
                atr14Percent,
                recentSupportPrice,
                quality == null ? ShortTermMomentumQuality.unavailable() : quality
        );
    }
}
