spring:
  config:
    import:
      - optional:nacos:ai-stock-api.yml?group=${NACOS_GROUP:AI_STOCK}
      - optional:nacos:ai-stock-api-${APP_ENV:local}.yml?group=${NACOS_GROUP:AI_STOCK}
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:AI_STOCK}
        file-extension: yml
        refresh-enabled: true
      discovery:
        enabled: true
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:AI_STOCK}
        service: ${spring.application.name}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
