CREATE TABLE IF NOT EXISTS trend_analysis_run (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_date DATE NOT NULL,
  request_fingerprint VARCHAR(64) NOT NULL,
  document_title VARCHAR(255) NOT NULL,
  document_type VARCHAR(128) NOT NULL,
  source_organization VARCHAR(128),
  published_at VARCHAR(32),
  source_url VARCHAR(1024),
  prompt_name VARCHAR(128) NOT NULL,
  prompt_version VARCHAR(32) NOT NULL,
  provider VARCHAR(64) NOT NULL,
  model VARCHAR(128) NOT NULL,
  response_id VARCHAR(128),
  request_payload TEXT NOT NULL,
  prompt_preview_payload TEXT NOT NULL,
  analysis_payload TEXT NOT NULL,
  usage_payload TEXT,
  analyzed_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uk_trend_analysis_run_day_fingerprint UNIQUE (analysis_date, request_fingerprint)
);

CREATE TABLE IF NOT EXISTS special_watchlist (
  symbol VARCHAR(6) PRIMARY KEY,
  company_name VARCHAR(128) NOT NULL,
  note VARCHAR(1000) NOT NULL DEFAULT '',
  last_action_label VARCHAR(64),
  last_decision_score NUMERIC(8, 2),
  last_analyzed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS market_kline_history (
  observation_id VARCHAR(64) PRIMARY KEY,
  symbol VARCHAR(6) NOT NULL,
  trade_date DATE NOT NULL,
  bar_type VARCHAR(32) NOT NULL,
  open_price NUMERIC(20, 6),
  close_price NUMERIC(20, 6),
  high_price NUMERIC(20, 6),
  low_price NUMERIC(20, 6),
  volume NUMERIC(30, 4),
  amount NUMERIC(30, 4),
  turnover_rate NUMERIC(12, 4),
  source_name VARCHAR(128) NOT NULL,
  observed_at TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE market_kline_history
  ADD COLUMN IF NOT EXISTS turnover_rate NUMERIC(12, 4);

CREATE INDEX IF NOT EXISTS idx_kline_symbol_date
  ON market_kline_history(symbol, trade_date, observed_at);

CREATE TABLE IF NOT EXISTS short_term_chip_verification (
  verification_key VARCHAR(160) PRIMARY KEY,
  symbol VARCHAR(12) NOT NULL,
  trade_date DATE NOT NULL,
  model_version VARCHAR(80) NOT NULL,
  verification_status VARCHAR(24) NOT NULL,
  verification_coefficient NUMERIC(8, 4) NOT NULL,
  average_cost_deviation NUMERIC(12, 6),
  cost_band_overlap NUMERIC(12, 6),
  winner_rate_deviation NUMERIC(12, 6),
  snapshot_json TEXT NOT NULL,
  external_summary_json TEXT,
  data_cutoff_at TIMESTAMP WITH TIME ZONE,
  observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
  error_summary VARCHAR(500),
  CONSTRAINT uq_short_term_chip_verification UNIQUE (symbol, trade_date, model_version)
);

CREATE INDEX IF NOT EXISTS idx_chip_verification_symbol_date
  ON short_term_chip_verification(symbol, trade_date, model_version);

CREATE TABLE IF NOT EXISTS research_analysis_history (
  analysis_id VARCHAR(36) PRIMARY KEY,
  symbol VARCHAR(6) NOT NULL,
  company_name VARCHAR(128) NOT NULL,
  analysis_type VARCHAR(64) NOT NULL,
  status VARCHAR(64) NOT NULL,
  summary VARCHAR(2000) NOT NULL,
  ai_provider VARCHAR(64),
  ai_model VARCHAR(128),
  payload_json TEXT NOT NULL,
  data_as_of TIMESTAMP WITH TIME ZONE NOT NULL,
  recorded_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_analysis_symbol_time
  ON research_analysis_history(symbol, recorded_at);

CREATE TABLE IF NOT EXISTS investment_decision_history (
  decision_id VARCHAR(36) PRIMARY KEY,
  analysis_id VARCHAR(36) NOT NULL,
  symbol VARCHAR(6) NOT NULL,
  source_type VARCHAR(64) NOT NULL,
  action_stage VARCHAR(64) NOT NULL,
  action_label VARCHAR(64) NOT NULL,
  decision_score NUMERIC(8, 2),
  rule_version VARCHAR(64) NOT NULL,
  payload_json TEXT NOT NULL,
  data_as_of TIMESTAMP WITH TIME ZONE NOT NULL,
  recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_decision_analysis FOREIGN KEY (analysis_id) REFERENCES research_analysis_history(analysis_id)
);

CREATE INDEX IF NOT EXISTS idx_decision_symbol_time
  ON investment_decision_history(symbol, recorded_at);

CREATE TABLE IF NOT EXISTS strategy_trade_case (
  case_id VARCHAR(36) PRIMARY KEY,
  recommendation_fingerprint VARCHAR(64) NOT NULL UNIQUE,
  decision_id VARCHAR(36),
  symbol VARCHAR(6) NOT NULL,
  company_name VARCHAR(128) NOT NULL,
  source_module VARCHAR(64) NOT NULL,
  recommendation_action VARCHAR(64) NOT NULL,
  recommendation_score NUMERIC(8, 2),
  rule_version VARCHAR(64) NOT NULL,
  recommended_price NUMERIC(20, 6) NOT NULL,
  recommended_at TIMESTAMP WITH TIME ZONE NOT NULL,
  recommendation_payload_json TEXT NOT NULL,
  recommendation_verified BOOLEAN NOT NULL DEFAULT FALSE,
  recommendation_attestation_id VARCHAR(64),
  status VARCHAR(32) NOT NULL,
  outcome_dirty BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_trade_case_decision FOREIGN KEY (decision_id)
    REFERENCES investment_decision_history(decision_id)
);

ALTER TABLE strategy_trade_case ADD COLUMN IF NOT EXISTS recommendation_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE strategy_trade_case ADD COLUMN IF NOT EXISTS recommendation_attestation_id VARCHAR(64);
ALTER TABLE strategy_trade_case ADD COLUMN IF NOT EXISTS outcome_dirty BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_trade_case_page
  ON strategy_trade_case(created_at, case_id);

CREATE INDEX IF NOT EXISTS idx_trade_case_status_page
  ON strategy_trade_case(status, created_at, case_id);

CREATE INDEX IF NOT EXISTS idx_trade_case_symbol_page
  ON strategy_trade_case(symbol, created_at, case_id);

CREATE INDEX IF NOT EXISTS idx_trade_case_refresh
  ON strategy_trade_case(status, updated_at, case_id);

CREATE INDEX IF NOT EXISTS idx_trade_case_dirty_refresh
  ON strategy_trade_case(outcome_dirty, status, updated_at, case_id);

CREATE TABLE IF NOT EXISTS strategy_trade_fill (
  fill_id VARCHAR(36) PRIMARY KEY,
  case_id VARCHAR(36) NOT NULL,
  side VARCHAR(8) NOT NULL,
  executed_at TIMESTAMP WITH TIME ZONE NOT NULL,
  price NUMERIC(20, 6) NOT NULL,
  quantity BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_trade_fill_case FOREIGN KEY (case_id) REFERENCES strategy_trade_case(case_id),
  CONSTRAINT ck_trade_fill_side CHECK (side IN ('BUY', 'SELL')),
  CONSTRAINT ck_trade_fill_price CHECK (price > 0),
  CONSTRAINT ck_trade_fill_quantity CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_trade_fill_feedback_lookup
  ON strategy_trade_fill(case_id, side, executed_at, created_at, fill_id);

CREATE TABLE IF NOT EXISTS strategy_trade_fill_revision (
  revision_id VARCHAR(36) PRIMARY KEY,
  fill_id VARCHAR(36) NOT NULL,
  case_id VARCHAR(36) NOT NULL,
  revision_sequence BIGINT NOT NULL,
  revision_type VARCHAR(16) NOT NULL,
  side VARCHAR(8) NOT NULL,
  executed_at TIMESTAMP WITH TIME ZONE NOT NULL,
  price NUMERIC(20, 6) NOT NULL,
  quantity BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_trade_fill_revision_fill FOREIGN KEY (fill_id) REFERENCES strategy_trade_fill(fill_id),
  CONSTRAINT fk_trade_fill_revision_case FOREIGN KEY (case_id) REFERENCES strategy_trade_case(case_id),
  CONSTRAINT ck_trade_fill_revision_type CHECK (revision_type IN ('CORRECTION', 'VOID')),
  CONSTRAINT ck_trade_fill_revision_side CHECK (side IN ('BUY', 'SELL')),
  CONSTRAINT ck_trade_fill_revision_price CHECK (price > 0),
  CONSTRAINT ck_trade_fill_revision_quantity CHECK (quantity > 0)
);

ALTER TABLE strategy_trade_fill_revision ADD COLUMN IF NOT EXISTS revision_sequence BIGINT;

UPDATE strategy_trade_fill_revision
SET revision_sequence = (
  SELECT COUNT(*)
  FROM strategy_trade_fill_revision prior_revision
  WHERE prior_revision.case_id = strategy_trade_fill_revision.case_id
    AND (
      prior_revision.created_at < strategy_trade_fill_revision.created_at
      OR (
        prior_revision.created_at = strategy_trade_fill_revision.created_at
        AND prior_revision.revision_id <= strategy_trade_fill_revision.revision_id
      )
    )
)
WHERE revision_sequence IS NULL;

ALTER TABLE strategy_trade_fill_revision ALTER COLUMN revision_sequence SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_trade_fill_revision_sequence
  ON strategy_trade_fill_revision(case_id, revision_sequence);

CREATE INDEX IF NOT EXISTS idx_trade_fill_revision_sequence_projection
  ON strategy_trade_fill_revision(case_id, fill_id, revision_sequence);

CREATE TABLE IF NOT EXISTS strategy_outcome_snapshot (
  snapshot_id VARCHAR(36) PRIMARY KEY,
  case_id VARCHAR(36) NOT NULL,
  baseline_type VARCHAR(32) NOT NULL,
  horizon VARCHAR(16) NOT NULL,
  baseline_price NUMERIC(20, 6),
  evaluation_price NUMERIC(20, 6),
  evaluation_date DATE,
  return_pct NUMERIC(12, 4),
  max_runup_pct NUMERIC(12, 4),
  max_drawdown_pct NUMERIC(12, 4),
  status VARCHAR(32) NOT NULL,
  source_name VARCHAR(128),
  market_timestamp TIMESTAMP WITH TIME ZONE,
  calculated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_trade_outcome_case FOREIGN KEY (case_id) REFERENCES strategy_trade_case(case_id),
  CONSTRAINT uk_trade_outcome_scope UNIQUE (case_id, baseline_type, horizon)
);

CREATE INDEX IF NOT EXISTS idx_trade_outcome_feedback_lookup
  ON strategy_outcome_snapshot(baseline_type, horizon, status, case_id);

ALTER TABLE strategy_outcome_snapshot ADD COLUMN IF NOT EXISTS source_name VARCHAR(128);
ALTER TABLE strategy_outcome_snapshot ADD COLUMN IF NOT EXISTS market_timestamp TIMESTAMP WITH TIME ZONE;

CREATE TABLE IF NOT EXISTS v2_quote_snapshot (
  snapshot_id VARCHAR(64) PRIMARY KEY,
  symbol VARCHAR(6) NOT NULL,
  company_name VARCHAR(128) NOT NULL,
  quote_stage VARCHAR(32) NOT NULL,
  last_price NUMERIC(20, 6),
  amount NUMERIC(30, 4),
  effective_at TIMESTAMP WITH TIME ZONE NOT NULL,
  available_at TIMESTAMP WITH TIME ZONE NOT NULL,
  ingested_at TIMESTAMP WITH TIME ZONE NOT NULL,
  source VARCHAR(128) NOT NULL,
  source_version VARCHAR(128) NOT NULL,
  quality_status VARCHAR(32) NOT NULL,
  raw_payload_hash VARCHAR(64) NOT NULL,
  raw_payload_json TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_v2_quote_visible
  ON v2_quote_snapshot(symbol, quote_stage, available_at, ingested_at);

CREATE INDEX IF NOT EXISTS idx_v2_quote_quality
  ON v2_quote_snapshot(quality_status, symbol, available_at);

CREATE TABLE IF NOT EXISTS v2_factor_snapshot (
  snapshot_id VARCHAR(64) PRIMARY KEY,
  strategy_code VARCHAR(64) NOT NULL,
  strategy_version VARCHAR(64) NOT NULL,
  factor_code VARCHAR(64) NOT NULL,
  symbol VARCHAR(6) NOT NULL,
  raw_value NUMERIC(24, 8),
  normalized_value NUMERIC(8, 2),
  data_confidence_impact NUMERIC(8, 2) NOT NULL,
  value_unit VARCHAR(32) NOT NULL,
  missing_reason VARCHAR(255) NOT NULL,
  available_at TIMESTAMP WITH TIME ZONE NOT NULL,
  calculated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  source_snapshot_id VARCHAR(64),
  payload_json TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_v2_factor_symbol_strategy
  ON v2_factor_snapshot(symbol, strategy_code, strategy_version, available_at);

CREATE INDEX IF NOT EXISTS idx_v2_factor_code_available
  ON v2_factor_snapshot(factor_code, available_at);

CREATE TABLE IF NOT EXISTS v2_recommendation_ledger (
  ledger_id VARCHAR(64) PRIMARY KEY,
  recommendation_fingerprint VARCHAR(64) NOT NULL UNIQUE,
  strategy_code VARCHAR(64) NOT NULL,
  strategy_version VARCHAR(64) NOT NULL,
  symbol VARCHAR(6) NOT NULL,
  company_name VARCHAR(128) NOT NULL,
  decision_at TIMESTAMP WITH TIME ZONE NOT NULL,
  data_cutoff_at TIMESTAMP WITH TIME ZONE NOT NULL,
  candidate_stage VARCHAR(32) NOT NULL,
  action VARCHAR(32) NOT NULL,
  signal_provenance VARCHAR(32) NOT NULL,
  rank_score NUMERIC(8, 2),
  data_confidence NUMERIC(8, 2),
  historical_hit_rate NUMERIC(8, 2),
  risk_reward NUMERIC(8, 2),
  payload_json TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE v2_recommendation_ledger
  ADD COLUMN IF NOT EXISTS signal_provenance VARCHAR(32) NOT NULL DEFAULT 'RULE_ENGINE';

CREATE INDEX IF NOT EXISTS idx_v2_ledger_symbol_time
  ON v2_recommendation_ledger(symbol, decision_at, ledger_id);

CREATE INDEX IF NOT EXISTS idx_v2_ledger_symbol_provenance_time
  ON v2_recommendation_ledger(symbol, signal_provenance, decision_at, ledger_id);

CREATE INDEX IF NOT EXISTS idx_v2_ledger_strategy_time
  ON v2_recommendation_ledger(strategy_code, strategy_version, decision_at);

DROP TABLE IF EXISTS short_term_scheduled_snapshot;

CREATE TABLE IF NOT EXISTS short_term_signal_observation (
  observation_id VARCHAR(64) PRIMARY KEY,
  publication_key VARCHAR(160) NOT NULL,
  publication_type VARCHAR(32) NOT NULL,
  strategy_version VARCHAR(80) NOT NULL,
  symbol VARCHAR(6) NOT NULL,
  company_name VARCHAR(128) NOT NULL,
  candidate_rank INTEGER NOT NULL,
  action VARCHAR(64) NOT NULL,
  signal_family VARCHAR(80) NOT NULL,
  market_regime VARCHAR(64) NOT NULL,
  recommendation_price NUMERIC(20, 6),
  recommendation_trade_date DATE,
  data_cutoff_at TIMESTAMP WITH TIME ZONE,
  published_at TIMESTAMP WITH TIME ZONE NOT NULL,
  source_name VARCHAR(128) NOT NULL,
  coverage_ratio NUMERIC(10, 6),
  coverage_expected_count INTEGER NOT NULL,
  coverage_fetched_count INTEGER NOT NULL,
  validation_eligible BOOLEAN NOT NULL,
  calibration_eligible BOOLEAN NOT NULL,
  validation_block_reason VARCHAR(1000),
  payload_json TEXT NOT NULL,
  buy_commission_percent NUMERIC(10, 6) NOT NULL,
  sell_commission_percent NUMERIC(10, 6) NOT NULL,
  sell_stamp_duty_percent NUMERIC(10, 6) NOT NULL,
  buy_slippage_percent NUMERIC(10, 6) NOT NULL,
  sell_slippage_percent NUMERIC(10, 6) NOT NULL,
  outcome_state VARCHAR(32) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_short_term_observation_publication UNIQUE (publication_key, symbol)
);

ALTER TABLE short_term_signal_observation
  ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_short_term_observation_pending
  ON short_term_signal_observation(validation_eligible, outcome_state, published_at, observation_id);

CREATE INDEX IF NOT EXISTS idx_short_term_observation_cohort
  ON short_term_signal_observation(
    calibration_eligible, strategy_version, signal_family, market_regime, observation_id);

CREATE TABLE IF NOT EXISTS short_term_signal_outcome (
  outcome_id VARCHAR(64) PRIMARY KEY,
  observation_id VARCHAR(64) NOT NULL,
  horizon VARCHAR(8) NOT NULL,
  target_trade_date DATE NOT NULL,
  evaluation_price NUMERIC(20, 6),
  gross_return_percent NUMERIC(14, 6),
  net_return_percent NUMERIC(14, 6),
  max_favorable_excursion_percent NUMERIC(14, 6),
  max_adverse_excursion_percent NUMERIC(14, 6),
  status VARCHAR(64) NOT NULL,
  source_name VARCHAR(128),
  market_timestamp TIMESTAMP WITH TIME ZONE,
  detail VARCHAR(1000),
  calculated_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_short_term_outcome_observation
    FOREIGN KEY (observation_id) REFERENCES short_term_signal_observation(observation_id),
  CONSTRAINT uk_short_term_outcome_horizon UNIQUE (observation_id, horizon)
);

ALTER TABLE short_term_signal_outcome
  ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_short_term_outcome_lookup
  ON short_term_signal_outcome(observation_id, horizon, status);

CREATE TABLE IF NOT EXISTS runtime_config_section (
  section_key VARCHAR(64) PRIMARY KEY,
  payload_json TEXT NOT NULL,
  revision BIGINT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

DROP TABLE IF EXISTS short_term_leader_snapshot;
