CREATE TABLE IF NOT EXISTS trend_analysis_run (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_date DATE NOT NULL,
  request_fingerprint VARCHAR(64) NOT NULL,
  document_title VARCHAR(255) NOT NULL,
  document_type VARCHAR(128) NOT NULL,
  source_organization VARCHAR(128),
  published_at VARCHAR(32),
  source_url VARCHAR(1024),
  prompt_name VARCHAR(128) NOT NULL,
  prompt_version VARCHAR(32) NOT NULL,
  provider VARCHAR(64) NOT NULL,
  model VARCHAR(128) NOT NULL,
  response_id VARCHAR(128),
  request_payload TEXT NOT NULL,
  prompt_preview_payload TEXT NOT NULL,
  analysis_payload TEXT NOT NULL,
  usage_payload TEXT,
  analyzed_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uk_trend_analysis_run_day_fingerprint UNIQUE (analysis_date, request_fingerprint)
);

CREATE TABLE IF NOT EXISTS special_watchlist (
  symbol VARCHAR(6) PRIMARY KEY,
  company_name VARCHAR(128) NOT NULL,
  note VARCHAR(1000) NOT NULL DEFAULT '',
  last_action_label VARCHAR(64),
  last_decision_score NUMERIC(8, 2),
  last_analyzed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS market_kline_history (
  observation_id VARCHAR(64) PRIMARY KEY,
  symbol VARCHAR(6) NOT NULL,
  trade_date DATE NOT NULL,
  bar_type VARCHAR(32) NOT NULL,
  open_price NUMERIC(20, 6),
  close_price NUMERIC(20, 6),
  high_price NUMERIC(20, 6),
  low_price NUMERIC(20, 6),
  volume NUMERIC(30, 4),
  amount NUMERIC(30, 4),
  source_name VARCHAR(128) NOT NULL,
  observed_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_kline_symbol_date
  ON market_kline_history(symbol, trade_date, observed_at);

CREATE TABLE IF NOT EXISTS research_analysis_history (
  analysis_id VARCHAR(36) PRIMARY KEY,
  symbol VARCHAR(6) NOT NULL,
  company_name VARCHAR(128) NOT NULL,
  analysis_type VARCHAR(64) NOT NULL,
  status VARCHAR(64) NOT NULL,
  summary VARCHAR(2000) NOT NULL,
  ai_provider VARCHAR(64),
  ai_model VARCHAR(128),
  payload_json TEXT NOT NULL,
  data_as_of TIMESTAMP WITH TIME ZONE NOT NULL,
  recorded_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_analysis_symbol_time
  ON research_analysis_history(symbol, recorded_at);

CREATE TABLE IF NOT EXISTS investment_decision_history (
  decision_id VARCHAR(36) PRIMARY KEY,
  analysis_id VARCHAR(36) NOT NULL,
  symbol VARCHAR(6) NOT NULL,
  source_type VARCHAR(64) NOT NULL,
  action_stage VARCHAR(64) NOT NULL,
  action_label VARCHAR(64) NOT NULL,
  decision_score NUMERIC(8, 2),
  rule_version VARCHAR(64) NOT NULL,
  payload_json TEXT NOT NULL,
  data_as_of TIMESTAMP WITH TIME ZONE NOT NULL,
  recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_decision_analysis FOREIGN KEY (analysis_id) REFERENCES research_analysis_history(analysis_id)
);

CREATE INDEX IF NOT EXISTS idx_decision_symbol_time
  ON investment_decision_history(symbol, recorded_at);

CREATE TABLE IF NOT EXISTS strategy_trade_case (
  case_id VARCHAR(36) PRIMARY KEY,
  recommendation_fingerprint VARCHAR(64) NOT NULL UNIQUE,
  decision_id VARCHAR(36),
  symbol VARCHAR(6) NOT NULL,
  company_name VARCHAR(128) NOT NULL,
  source_module VARCHAR(64) NOT NULL,
  recommendation_action VARCHAR(64) NOT NULL,
  recommendation_score NUMERIC(8, 2),
  rule_version VARCHAR(64) NOT NULL,
  recommended_price NUMERIC(20, 6) NOT NULL,
  recommended_at TIMESTAMP WITH TIME ZONE NOT NULL,
  recommendation_payload_json TEXT NOT NULL,
  recommendation_verified BOOLEAN NOT NULL DEFAULT FALSE,
  recommendation_attestation_id VARCHAR(64),
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_trade_case_decision FOREIGN KEY (decision_id)
    REFERENCES investment_decision_history(decision_id)
);

ALTER TABLE strategy_trade_case ADD COLUMN IF NOT EXISTS recommendation_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE strategy_trade_case ADD COLUMN IF NOT EXISTS recommendation_attestation_id VARCHAR(64);

CREATE INDEX IF NOT EXISTS idx_trade_case_page
  ON strategy_trade_case(created_at, case_id);

CREATE INDEX IF NOT EXISTS idx_trade_case_status_page
  ON strategy_trade_case(status, created_at, case_id);

CREATE INDEX IF NOT EXISTS idx_trade_case_symbol_page
  ON strategy_trade_case(symbol, created_at, case_id);

CREATE INDEX IF NOT EXISTS idx_trade_case_refresh
  ON strategy_trade_case(status, updated_at, case_id);

CREATE TABLE IF NOT EXISTS strategy_trade_fill (
  fill_id VARCHAR(36) PRIMARY KEY,
  case_id VARCHAR(36) NOT NULL,
  side VARCHAR(8) NOT NULL,
  executed_at TIMESTAMP WITH TIME ZONE NOT NULL,
  price NUMERIC(20, 6) NOT NULL,
  quantity BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_trade_fill_case FOREIGN KEY (case_id) REFERENCES strategy_trade_case(case_id),
  CONSTRAINT ck_trade_fill_side CHECK (side IN ('BUY', 'SELL')),
  CONSTRAINT ck_trade_fill_price CHECK (price > 0),
  CONSTRAINT ck_trade_fill_quantity CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_trade_fill_feedback_lookup
  ON strategy_trade_fill(case_id, side, executed_at, created_at, fill_id);

CREATE TABLE IF NOT EXISTS strategy_trade_fill_revision (
  revision_id VARCHAR(36) PRIMARY KEY,
  fill_id VARCHAR(36) NOT NULL,
  case_id VARCHAR(36) NOT NULL,
  revision_type VARCHAR(16) NOT NULL,
  side VARCHAR(8) NOT NULL,
  executed_at TIMESTAMP WITH TIME ZONE NOT NULL,
  price NUMERIC(20, 6) NOT NULL,
  quantity BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_trade_fill_revision_fill FOREIGN KEY (fill_id) REFERENCES strategy_trade_fill(fill_id),
  CONSTRAINT fk_trade_fill_revision_case FOREIGN KEY (case_id) REFERENCES strategy_trade_case(case_id),
  CONSTRAINT ck_trade_fill_revision_type CHECK (revision_type IN ('CORRECTION', 'VOID')),
  CONSTRAINT ck_trade_fill_revision_side CHECK (side IN ('BUY', 'SELL')),
  CONSTRAINT ck_trade_fill_revision_price CHECK (price > 0),
  CONSTRAINT ck_trade_fill_revision_quantity CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_trade_fill_revision_projection
  ON strategy_trade_fill_revision(case_id, fill_id, created_at, revision_id);

CREATE TABLE IF NOT EXISTS strategy_outcome_snapshot (
  snapshot_id VARCHAR(36) PRIMARY KEY,
  case_id VARCHAR(36) NOT NULL,
  baseline_type VARCHAR(32) NOT NULL,
  horizon VARCHAR(16) NOT NULL,
  baseline_price NUMERIC(20, 6),
  evaluation_price NUMERIC(20, 6),
  evaluation_date DATE,
  return_pct NUMERIC(12, 4),
  max_runup_pct NUMERIC(12, 4),
  max_drawdown_pct NUMERIC(12, 4),
  status VARCHAR(32) NOT NULL,
  source_name VARCHAR(128),
  market_timestamp TIMESTAMP WITH TIME ZONE,
  calculated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_trade_outcome_case FOREIGN KEY (case_id) REFERENCES strategy_trade_case(case_id),
  CONSTRAINT uk_trade_outcome_scope UNIQUE (case_id, baseline_type, horizon)
);

CREATE INDEX IF NOT EXISTS idx_trade_outcome_feedback_lookup
  ON strategy_outcome_snapshot(baseline_type, horizon, status, case_id);

ALTER TABLE strategy_outcome_snapshot ADD COLUMN IF NOT EXISTS source_name VARCHAR(128);
ALTER TABLE strategy_outcome_snapshot ADD COLUMN IF NOT EXISTS market_timestamp TIMESTAMP WITH TIME ZONE;
